"""Spot Practice Trainer — drill library + real LivePokerTable game.

Two views:
  LIBRARY  — browse / filter drills, play individual or run a queue
  PLAY     — real PokerGame with bots, solver feedback panel on the right

Drills can come from the built-in seed set OR be generated by LeakFinder
via the shared DrillLibrary singleton.
"""
from __future__ import annotations

from PySide6.QtCore import Qt, Signal, QTimer
from PySide6.QtGui import QFont, QKeySequence, QShortcut
from PySide6.QtWidgets import (
    QComboBox, QFrame, QGridLayout, QHBoxLayout, QLabel,
    QPushButton, QScrollArea, QSizePolicy, QSlider,
    QVBoxLayout, QWidget,
)

from app.ai.coach_engine import explain_spot
from app.core.app_state import AppState
from app.engine.game_loop import PokerGame
from app.engine.hand_state import ActionType, Street
from app.solver.mock_solver import compare_action, solve_spot
from app.training.drill_library import DrillLibrary
from app.training.trainer_scoring import score_decision, skill_label
from app.ui.components.poker_table import LivePokerTable, seats_from_hand
from app.ui.components.solver_bar import EVLossBadge, SolverFrequencyBar


# ── colour palette (mirrors dark_flat theme) ────────────────────────────
_GREEN  = "#5ad17a"
_CYAN   = "#5ad1ce"
_AMBER  = "#f0a500"
_RED    = "#e87474"
_DARK   = "#0f1210"
_PANEL  = "#131613"
_BORDER = "#23271f"
_MUTED  = "#5a5e54"

_CAT_COLOURS = {
    "seeded": (_MUTED, _BORDER),
    "leak":   (_RED, "#3a1414"),
}

_SEVERITY_COL = {"Critical": _RED, "High": _AMBER, "Medium": _CYAN, "Low": _MUTED}


# ── helpers ─────────────────────────────────────────────────────────────

def _label(text: str, obj: str = "TLabel") -> QLabel:
    l = QLabel(text)
    l.setObjectName(obj)
    return l


def _mono(text: str = "", size: int = 11) -> QLabel:
    l = QLabel(text)
    l.setStyleSheet(
        f"font-family:'JetBrains Mono',monospace; font-size:{size}px; color:#898d80;"
    )
    return l


def _sep() -> QFrame:
    f = QFrame()
    f.setFrameShape(QFrame.HLine)
    f.setStyleSheet(f"background:{_BORDER}; border:none; max-height:1px;")
    return f


def _clear(layout) -> None:
    while layout.count():
        item = layout.takeAt(0)
        w = item.widget()
        child = item.layout()
        if w:
            w.deleteLater()
        if child:
            _clear(child)


def _table_size(table_str: str) -> int:
    """Return number of players (including hero) from a table string."""
    if "HU" in table_str or "Heads" in table_str:
        return 2
    if "9" in table_str:
        return 9
    return 6   # default 6-max


def _action_str(action_type: ActionType, hand, size_bb: float) -> str:
    """Map engine ActionType to a drill option string."""
    if action_type == ActionType.FOLD:
        return "fold"
    if action_type == ActionType.CHECK:
        return "check"
    if action_type == ActionType.CALL:
        return "call"
    if action_type == ActionType.ALL_IN:
        return "jam"
    # RAISE / BET — classify by sizing relative to pot
    pot = max(hand.pot, 0.01)
    ratio = size_bb / pot
    if ratio <= 0.40:
        return "bet small"
    if ratio <= 0.70:
        return "bet medium"
    if ratio <= 1.10:
        return "bet large"
    return "raise"


# ════════════════════════════════════════════════════════════════════════
# Drill card widget — used in library view
# ════════════════════════════════════════════════════════════════════════

class _DrillCard(QFrame):
    play_clicked = Signal(dict)   # emits the drill dict

    def __init__(self, drill: dict, score: int | None):
        super().__init__()
        self.drill = drill
        self.setObjectName("Card")
        self.setFrameShape(QFrame.StyledPanel)

        row = QHBoxLayout(self)
        row.setContentsMargins(12, 8, 12, 8)
        row.setSpacing(12)

        # Source badge
        source = drill.get("source", "seeded")
        fg, bg = _CAT_COLOURS.get(source, (_MUTED, _BORDER))
        badge = QLabel(source.upper())
        badge.setFixedWidth(52)
        badge.setAlignment(Qt.AlignCenter)
        badge.setStyleSheet(
            f"font-family:'JetBrains Mono',monospace; font-size:9px; font-weight:700;"
            f"color:{fg}; background:{bg}; border:1px solid {fg}; padding:2px 4px;"
        )
        row.addWidget(badge)

        # Info block
        info = QVBoxLayout()
        info.setSpacing(2)
        title_lbl = QLabel(f"{drill.get('id','')}  ·  {drill.get('title','')}")
        title_lbl.setObjectName("SectionTitle")
        title_lbl.setStyleSheet("font-size:12px; font-weight:700;")
        meta_lbl = QLabel(
            f"{drill.get('street','').title()}  ·  {drill.get('table','6-max')}  ·  "
            f"{drill.get('stack_bb',100)}bb  ·  {drill.get('format','cash')}"
        )
        meta_lbl.setObjectName("Muted")
        meta_lbl.setStyleSheet("font-size:10px;")
        info.addWidget(title_lbl)
        info.addWidget(meta_lbl)
        if drill.get("source") == "leak":
            leak_lbl = QLabel(f"⚑ Leak: {drill.get('leak_name','')}")
            sev_col = _SEVERITY_COL.get(drill.get("severity", "Medium"), _MUTED)
            leak_lbl.setStyleSheet(f"font-family:'JetBrains Mono',monospace; font-size:9px; color:{sev_col};")
            info.addWidget(leak_lbl)
        row.addLayout(info, 1)

        # Score chip
        if score is not None:
            col = _GREEN if score >= 80 else (_AMBER if score >= 60 else _RED)
            sc_lbl = QLabel(f"{score}/100")
            sc_lbl.setAlignment(Qt.AlignCenter)
            sc_lbl.setFixedWidth(52)
            sc_lbl.setStyleSheet(
                f"font-family:'JetBrains Mono',monospace; font-size:10px; "
                f"font-weight:700; color:{col};"
            )
            row.addWidget(sc_lbl)

        # Play button
        play_btn = QPushButton("▶  PLAY")
        play_btn.setObjectName("PrimaryButton")
        play_btn.setFixedWidth(80)
        play_btn.setMinimumHeight(32)
        play_btn.clicked.connect(lambda: self.play_clicked.emit(self.drill))
        row.addWidget(play_btn)


# ════════════════════════════════════════════════════════════════════════
# Main screen
# ════════════════════════════════════════════════════════════════════════

class SpotTrainerScreen(QWidget):
    coach_message = Signal(str)

    def __init__(self, state: AppState):
        super().__init__()
        self.state = state
        self.lib = DrillLibrary.instance()
        self.lib.drill_added.connect(self._on_drill_added)

        # Game state
        self._game: PokerGame | None = None
        self._bot_timer = QTimer(self)
        self._bot_timer.setInterval(420)
        self._bot_timer.timeout.connect(self._tick_bot)

        # Drill queue
        self._queue: list[dict] = []
        self._q_idx: int = 0
        self._current_drill: dict | None = None
        self._shortcuts: list = []

        # Root
        self._root_layout = QVBoxLayout(self)
        self._root_layout.setContentsMargins(0, 0, 0, 0)
        self._root_layout.setSpacing(0)

        # Top bar (always visible)
        self._build_topbar()

        # View container (swapped between library & play)
        self._view = QWidget()
        self._view_layout = QVBoxLayout(self._view)
        self._view_layout.setContentsMargins(0, 0, 0, 0)
        self._root_layout.addWidget(self._view, 1)

        self._show_library()

    # ── Top bar ────────────────────────────────────────────────────────

    def _build_topbar(self) -> None:
        bar = QFrame()
        bar.setObjectName("TopBar")
        bl = QHBoxLayout(bar)
        bl.setContentsMargins(18, 10, 18, 10)

        title = QLabel("Spot Practice Trainer")
        title.setObjectName("Title")
        bl.addWidget(title)
        bl.addStretch(1)

        self._lib_btn = QPushButton("⊞  DRILL LIBRARY")
        self._lib_btn.setCheckable(True)
        self._lib_btn.setChecked(True)
        self._lib_btn.clicked.connect(self._show_library)

        for mode in ["Quick drill", "Timed mode", "Mistakes-only", "Boss battle"]:
            btn = QPushButton(mode)
            btn.clicked.connect(
                lambda _=False, m=mode:
                self.coach_message.emit(f"{m} modu aktif. Demo solver ile feedback.")
            )
            bl.addWidget(btn)

        bl.addWidget(self._lib_btn)
        self._root_layout.addWidget(bar)

        # Score ribbon (hidden in library view)
        self._score_bar = QFrame()
        self._score_bar.setStyleSheet(f"background:{_PANEL}; border-bottom:1px solid {_BORDER};")
        sb = QHBoxLayout(self._score_bar)
        sb.setContentsMargins(18, 5, 18, 5)
        self._score_queue_lbl = _mono("—")
        self._score_total_lbl = _mono("Score: —")
        sb.addWidget(self._score_queue_lbl)
        sb.addStretch(1)
        sb.addWidget(self._score_total_lbl)
        self._root_layout.addWidget(self._score_bar)
        self._score_bar.hide()

    # ── View switching ─────────────────────────────────────────────────

    def _clear_view(self) -> None:
        _clear(self._view_layout)
        self._stop_game()

    def _show_library(self) -> None:
        self._lib_btn.setChecked(True)
        self._score_bar.hide()
        self._clear_view()
        self._build_library()

    def _show_play(self) -> None:
        self._lib_btn.setChecked(False)
        self._score_bar.show()
        self._clear_view()
        self._build_play()

    # ── LIBRARY VIEW ───────────────────────────────────────────────────

    def _build_library(self) -> None:
        scroll = QScrollArea()
        scroll.setWidgetResizable(True)
        scroll.setFrameShape(QFrame.NoFrame)
        body = QWidget()
        scroll.setWidget(body)
        layout = QVBoxLayout(body)
        layout.setContentsMargins(20, 16, 20, 24)
        layout.setSpacing(12)

        # ── filter row ────────────────────────────────────────────────
        filter_row = QHBoxLayout()
        filter_row.setSpacing(8)
        cat_lbl = _label("CATEGORY")
        self._cat_combo = QComboBox()
        self._cat_combo.addItems(["All", "Preflop", "Flop", "Turn", "River"])
        self._cat_combo.currentTextChanged.connect(self._refresh_library)
        src_lbl = _label("SOURCE")
        self._src_combo = QComboBox()
        self._src_combo.addItems(["All", "Seeded", "From Leaks", "🔁 Hatalarım"])
        self._src_combo.currentTextChanged.connect(self._refresh_library)

        queue_all_btn = QPushButton("▶▶  START ALL DRILLS")
        queue_all_btn.setObjectName("PrimaryButton")
        queue_all_btn.setMinimumHeight(34)
        queue_all_btn.clicked.connect(self._start_all_queue)

        filter_row.addWidget(cat_lbl)
        filter_row.addWidget(self._cat_combo)
        filter_row.addWidget(src_lbl)
        filter_row.addWidget(self._src_combo)
        filter_row.addStretch(1)
        filter_row.addWidget(queue_all_btn)
        layout.addLayout(filter_row)
        layout.addWidget(_sep())

        # ── drill cards container ──────────────────────────────────────
        self._cards_widget = QWidget()
        self._cards_layout = QVBoxLayout(self._cards_widget)
        self._cards_layout.setSpacing(6)
        self._cards_layout.setContentsMargins(0, 0, 0, 0)
        layout.addWidget(self._cards_widget)
        layout.addStretch(1)

        self._view_layout.addWidget(scroll)
        self._refresh_library()

    def _refresh_library(self) -> None:
        _clear(self._cards_layout)

        cat = self._cat_combo.currentText() if hasattr(self, "_cat_combo") else "All"
        src = self._src_combo.currentText() if hasattr(self, "_src_combo") else "All"

        if "Hatalar" in src:
            # GERÇEK oynanmış hata spotları (board/kart/pozisyon ile yeniden oyna)
            try:
                from app.db.repository import get_mistake_spots
                drills = get_mistake_spots()
            except Exception:
                drills = []
            if not drills:
                self._cards_layout.addWidget(_mono(
                    "Henüz kayıtlı hata spotun yok. Real Experience modda el oyna; "
                    "GTO'dan saptığın gerçek eller buraya düşecek."))
                return
        else:
            drills = self.lib.get_drills(cat)
            if src == "Seeded":
                drills = [d for d in drills if d.get("source") == "seeded"]
            elif src == "From Leaks":
                drills = [d for d in drills if d.get("source") == "leak"]
            if not drills:
                self._cards_layout.addWidget(_mono("Henüz bu kategoride drill yok."))
                return

        for drill in drills:
            score = self.lib.get_score(drill["id"])
            card = _DrillCard(drill, score)
            card.play_clicked.connect(self._play_single)
            self._cards_layout.addWidget(card)

    def _on_drill_added(self, _drill: dict) -> None:
        """Called when LeakFinder adds a new drill — refresh library if visible."""
        if hasattr(self, "_cards_layout") and self._cards_layout.parent():
            self._refresh_library()

    # ── Queue logic ────────────────────────────────────────────────────

    def _start_all_queue(self) -> None:
        cat = self._cat_combo.currentText() if hasattr(self, "_cat_combo") else "All"
        self._queue = self.lib.get_drills(cat)[:30]   # cap at 30
        self._q_idx = 0
        self._play_next()

    def _play_single(self, drill: dict) -> None:
        self._queue = [drill]
        self._q_idx = 0
        self._play_next()

    def _play_next(self) -> None:
        if self._q_idx >= len(self._queue):
            self._on_queue_done()
            return
        self._current_drill = self._queue[self._q_idx]
        self._q_idx += 1
        self._update_score_bar()
        self._show_play()

    def _on_queue_done(self) -> None:
        self.coach_message.emit(
            f"Queue tamamlandı! {self._q_idx} drill oynadın. "
            "Drill Library'ye dönüyorsun — sonuçlar kaydedildi."
        )
        self._show_library()

    def _update_score_bar(self) -> None:
        total = len(self._queue)
        idx = self._q_idx
        self._score_queue_lbl.setText(
            f"DRILL  {idx} / {total}  ·  {self._current_drill['id'] if self._current_drill else '—'}"
        )

    # ── PLAY VIEW ──────────────────────────────────────────────────────

    def _build_play(self) -> None:
        """Build the two-panel play layout + action deck."""
        drill = self._current_drill
        if drill is None:
            return

        # ── Start real PokerGame matching drill parameters ─────────────
        n_players = _table_size(drill.get("table", "6-max"))
        stack_bb  = float(drill.get("stack_bb", 100))
        n_bots    = max(1, n_players - 1)
        archetypes = (["TAG", "Reg", "LAG", "Fish", "Tight Passive",
                       "Reg", "TAG", "Fish"] * 3)[:n_bots]

        self._game = PokerGame(
            num_players=n_players,
            starting_stack=stack_bb,
            small_blind=0.5,
            big_blind=1.0,
            hero_seat=0,
            bot_archetypes=archetypes,
            paced_bots=True,
        )

        # Outer page
        page = QFrame()
        pl = QVBoxLayout(page)
        pl.setContentsMargins(0, 0, 0, 0)
        pl.setSpacing(0)

        # ── CONTENT ROW: table (left) + drill panel (right) ────────────
        content = QWidget()
        cl = QHBoxLayout(content)
        cl.setContentsMargins(0, 0, 0, 0)
        cl.setSpacing(0)

        # LEFT: poker table
        self.table = LivePokerTable()
        self.table.set_unit("bb")
        self.table.setMinimumHeight(400)
        cl.addWidget(self.table, 3)

        # RIGHT: drill panel
        right = QFrame()
        right.setObjectName("DataPanel")
        right.setMinimumWidth(280)
        right.setMaximumWidth(380)
        rl = QVBoxLayout(right)
        rl.setContentsMargins(16, 14, 16, 14)
        rl.setSpacing(8)

        # Back button
        back_btn = QPushButton("← LIBRARY")
        back_btn.setObjectName("GhostButton")
        back_btn.setFixedHeight(28)
        back_btn.clicked.connect(self._show_library)
        rl.addWidget(back_btn)
        rl.addWidget(_sep())

        # Drill metadata
        drill_id_lbl = QLabel(f"{drill.get('id','')}  ·  {drill.get('street','').upper()}")
        drill_id_lbl.setObjectName("Mono")
        drill_id_lbl.setStyleSheet("font-size:10px; color:#5ad1ce;")

        drill_title_lbl = QLabel(drill.get("title", ""))
        drill_title_lbl.setObjectName("SectionTitle")
        drill_title_lbl.setWordWrap(True)
        drill_title_lbl.setStyleSheet("font-size:12px;")

        drill_meta_lbl = QLabel(
            f"{drill.get('format','cash')} · {drill.get('table','6-max')} · "
            f"{drill.get('stack_bb',100)}bb · {drill.get('pot_type','SRP')}"
        )
        drill_meta_lbl.setObjectName("Muted")
        drill_meta_lbl.setWordWrap(True)
        drill_meta_lbl.setStyleSheet("font-size:10px;")

        history_lbl = QLabel(drill.get("action_history", ""))
        history_lbl.setObjectName("Cyan")
        history_lbl.setWordWrap(True)
        history_lbl.setStyleSheet("font-size:10px;")

        rl.addWidget(drill_id_lbl)
        rl.addWidget(drill_title_lbl)
        rl.addWidget(drill_meta_lbl)
        rl.addWidget(history_lbl)
        rl.addWidget(_sep())

        # Feedback / solver area (cleared & repopulated on each action)
        self._feedback_frame = QFrame()
        self._feedback_frame.setObjectName("DataPanel")
        self._feedback_layout = QVBoxLayout(self._feedback_frame)
        self._feedback_layout.setContentsMargins(0, 0, 0, 0)
        self._feedback_layout.setSpacing(6)
        rl.addWidget(self._feedback_frame, 1)

        rl.addStretch(1)

        # Next drill button (hidden until hand done)
        self._next_drill_btn = QPushButton("NEXT DRILL  ⎵")
        self._next_drill_btn.setObjectName("PrimaryButton")
        self._next_drill_btn.setMinimumHeight(36)
        self._next_drill_btn.hide()
        self._next_drill_btn.clicked.connect(self._play_next)
        rl.addWidget(self._next_drill_btn)

        cl.addWidget(right, 2)
        pl.addWidget(content, 1)

        # ── ACTION DECK ────────────────────────────────────────────────
        deck = QFrame()
        deck.setStyleSheet(f"background:{_DARK}; border-top:2px solid {_BORDER};")
        dv = QVBoxLayout(deck)
        dv.setContentsMargins(18, 8, 18, 12)
        dv.setSpacing(6)

        # To-call banner
        self._to_call_banner = QLabel("")
        self._to_call_banner.setAlignment(Qt.AlignCenter)
        self._to_call_banner.setStyleSheet(
            f"font-family:'JetBrains Mono',monospace; font-size:11px; font-weight:700;"
            f"letter-spacing:1.4px; color:{_GREEN}; padding:4px 12px;"
            f"border:1px solid #2a4a30; background:#0f1d11;"
        )
        self._to_call_banner.hide()
        banner_row = QHBoxLayout()
        banner_row.addStretch(1)
        banner_row.addWidget(self._to_call_banner)
        banner_row.addStretch(1)
        dv.addLayout(banner_row)

        # Deck row (sizing + actions)
        dl_container = QWidget()
        dl_container.setStyleSheet("background:transparent;")
        dl = QHBoxLayout(dl_container)
        dl.setSpacing(12)
        dl.setContentsMargins(0, 0, 0, 0)

        # Sizing controls
        sizing = QVBoxLayout()
        sizing.setSpacing(3)
        sizing.addWidget(_label("BET SIZE (% POT)"))
        preset_row = QHBoxLayout()
        preset_row.setSpacing(0)
        for pct, lbl in [(33, "33%"), (50, "50%"), (66, "66%"), (75, "75%"), (100, "POT"), (150, "1.5x")]:
            b = QPushButton(lbl)
            b.setObjectName("PresetButton")
            b.setCursor(Qt.PointingHandCursor)
            b.clicked.connect(lambda _=False, p=pct: self.size_slider.setValue(p))
            preset_row.addWidget(b)
        sizing.addLayout(preset_row)
        self.size_slider = QSlider(Qt.Horizontal)
        self.size_slider.setRange(1, 300)
        self.size_slider.setValue(66)
        self.size_slider.valueChanged.connect(self._refresh_size)
        self.size_label = QLabel("—")
        self.size_label.setStyleSheet(
            "font-family:'JetBrains Mono',monospace; font-size:13px;"
        )
        sizing.addWidget(self.size_slider)
        sizing.addWidget(self.size_label)
        dl.addLayout(sizing, 2)

        # Action buttons
        acts = QHBoxLayout()
        acts.setSpacing(6)
        self.fold_btn  = QPushButton("FOLD");   self.fold_btn.setObjectName("ActionFold")
        self.check_btn = QPushButton("CHECK");  self.check_btn.setObjectName("ActionCheck")
        self.call_btn  = QPushButton("CALL");   self.call_btn.setObjectName("ActionCall")
        self.raise_btn = QPushButton("RAISE");  self.raise_btn.setObjectName("ActionRaise")
        self.allin_btn = QPushButton("ALL-IN"); self.allin_btn.setObjectName("ActionAllin")

        self.fold_btn.clicked.connect(lambda: self._hero_action(ActionType.FOLD))
        self.check_btn.clicked.connect(lambda: self._hero_action(ActionType.CHECK))
        self.call_btn.clicked.connect(lambda: self._hero_action(ActionType.CALL))
        self.raise_btn.clicked.connect(lambda: self._hero_action(ActionType.RAISE))
        self.allin_btn.clicked.connect(lambda: self._hero_action(ActionType.ALL_IN))

        for b in (self.fold_btn, self.check_btn, self.call_btn, self.raise_btn, self.allin_btn):
            b.setMinimumWidth(72)
            b.setMinimumHeight(44)
            b.setCursor(Qt.PointingHandCursor)
            b.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
            acts.addWidget(b, 1)
        dl.addLayout(acts, 4)

        dl_scroll = QScrollArea()
        dl_scroll.setWidget(dl_container)
        dl_scroll.setWidgetResizable(True)
        dl_scroll.setFrameShape(QFrame.NoFrame)
        dl_scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        dl_scroll.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        dl_scroll.setStyleSheet("QScrollArea { background:transparent; border:none; }")
        dv.addWidget(dl_scroll, 1)
        pl.addWidget(deck)

        self._view_layout.addWidget(page)

        # Keyboard shortcuts
        self._shortcuts = [
            QShortcut(QKeySequence(Qt.Key_Space), self, activated=self._space_pressed),
            QShortcut(QKeySequence("F"), self, activated=lambda: self._key_action("F")),
            QShortcut(QKeySequence("C"), self, activated=lambda: self._key_action("C")),
            QShortcut(QKeySequence("R"), self, activated=lambda: self._key_action("R")),
            QShortcut(QKeySequence("A"), self, activated=lambda: self._key_action("A")),
            QShortcut(QKeySequence(Qt.Key_Escape), self, activated=self._show_library),
        ]

        # Show solver baseline in the right panel
        self._show_solver_preview()

        # Deal first hand
        self._deal_next()

    # ── Game loop ──────────────────────────────────────────────────────

    def _deal_next(self) -> None:
        if not self._game:
            return
        self._next_drill_btn.hide()
        self._game.start_hand()
        self._refresh()
        hand = self._game.current_hand
        if hand and not self._game.is_waiting_for_hero and not hand.is_complete:
            self._bot_timer.start()

    def _tick_bot(self) -> None:
        if not self._game or not self._game.current_hand:
            self._bot_timer.stop()
            return
        keep = self._game.step_action()
        self._refresh()
        if not keep:
            self._bot_timer.stop()
            if self._game.current_hand and self._game.current_hand.is_complete:
                self._on_hand_complete()

    def _hero_action(self, action_type: ActionType) -> None:
        if not self._game or not self._game.is_waiting_for_hero:
            return
        hand = self._game.current_hand
        hero = hand.hero
        amount = 0.0
        if action_type in (ActionType.BET, ActionType.RAISE):
            amount = self._size_bb()
        elif action_type == ActionType.CALL:
            amount = hand.to_call(hand.hero_idx)
        elif action_type == ActionType.ALL_IN:
            amount = hero.stack if hero else 0.0

        action_str = _action_str(action_type, hand, amount)
        self._game.hero_act(action_type, amount)
        self._refresh()

        if hand.is_complete:
            self._show_drill_feedback(action_str)
            self._on_hand_complete()
        else:
            self._bot_timer.start()

    def _on_hand_complete(self) -> None:
        self._next_drill_btn.show()
        self._update_buttons_visible()

    def _stop_game(self) -> None:
        if hasattr(self, "_bot_timer"):
            self._bot_timer.stop()
        for sc in getattr(self, "_shortcuts", []):
            sc.setEnabled(False)
            sc.deleteLater()
        self._shortcuts = []
        self._game = None

    # ── Refresh / render ───────────────────────────────────────────────

    def _refresh(self) -> None:
        if not self._game or not self._game.current_hand:
            return
        hand = self._game.current_hand
        hero = hand.hero

        action_top = self._game._action_queue[0] if self._game._action_queue else -1
        seats, hero_slot, dealer_slot = seats_from_hand(
            hand.players, hand.hero_idx,
            action_queue_top=action_top, unit="bb", hand=hand,
        )
        hero_cards = [c.display for c in hero.hole_cards] if (hero and hero.hole_cards) else None
        board = [c.display for c in hand.community]
        note = f"BLINDS {hand.small_blind:g}/{hand.big_blind:g}"

        hero_to_call = hand.to_call(hand.hero_idx) if hero else 0.0
        self.table.render_state(
            seats=seats,
            hero_slot_idx=hero_slot,
            dealer_slot_idx=dealer_slot,
            street=hand.street_name,
            board=board,
            pot=hand.pot,
            hero_cards=hero_cards,
            note=note,
            big_pot=(hand.street == Street.PREFLOP),
            show_opponent_backs=not hand.is_complete,
            to_call=hero_to_call,
        )

        if self._game.is_waiting_for_hero and hero_to_call > 0 and hand.pot > 0:
            pct = int(round(100 * hero_to_call / hand.pot))
            self._to_call_banner.setText(f"TO CALL  {hero_to_call:.1f} bb  ·  {pct}% POT")
            self._to_call_banner.show()
        else:
            self._to_call_banner.hide()

        self._update_buttons_visible()
        self._refresh_size()

    def _update_buttons_visible(self) -> None:
        for b in (self.fold_btn, self.check_btn, self.call_btn, self.raise_btn, self.allin_btn):
            b.hide()
        if not self._game or not self._game.is_waiting_for_hero:
            return
        hand = self._game.current_hand
        if not hand or hand.is_complete:
            return
        hero_idx = hand.hero_idx
        hero = hand.hero
        valid_types = {v[0] for v in hand.get_valid_actions(hero_idx)}
        to_call = hand.to_call(hero_idx)
        stk_ok = hero and hero.stack >= 0.05

        if ActionType.FOLD  in valid_types: self.fold_btn.show()
        if ActionType.CHECK in valid_types: self.check_btn.show()
        if ActionType.CALL  in valid_types:
            self.call_btn.setText(f"CALL  {to_call:.1f} bb")
            self.call_btn.show()
        elif to_call > 0 and ActionType.ALL_IN in valid_types and stk_ok:
            self.call_btn.setText(f"CALL ALL-IN  {hero.stack:.1f}")
            self.call_btn.show()
        if ActionType.BET   in valid_types:
            self.raise_btn.setText("BET"); self.raise_btn.show()
        if ActionType.RAISE in valid_types:
            self.raise_btn.setText("RAISE"); self.raise_btn.show()
        if stk_ok and to_call < hero.stack:
            self.allin_btn.setText(f"ALL-IN  {hero.stack:.1f}")
            self.allin_btn.show()

    def _size_bb(self) -> float:
        hand = self._game.current_hand
        hero = hand.hero
        pct = self.size_slider.value() / 100.0
        if hand.street == Street.PREFLOP and hand.pot <= hand.big_blind * 3:
            target = hand.big_blind * (2.0 + pct * 1.5)
        else:
            target = hand.pot * pct
        floor = max(hand.last_full_raise_size, hand.big_blind)
        if hand.current_bet > 0:
            target = max(target, hand.current_bet + floor - hero.current_bet)
        else:
            target = max(target, hand.big_blind)
        return round(min(target, hero.stack), 2)

    def _refresh_size(self) -> None:
        if not self._game or not self._game.current_hand:
            return
        chips = self._size_bb()
        pot = max(self._game.current_hand.pot, 0.01)
        pct = int(round(100 * chips / pot))
        self.size_label.setText(f"{chips:.1f} bb  ·  {pct}% pot")

    # ── Solver preview & feedback ──────────────────────────────────────

    def _show_solver_preview(self) -> None:
        _clear(self._feedback_layout)
        drill = self._current_drill
        if drill is None:
            return
        result = solve_spot(drill)
        hdr = QLabel("SOLVER BASELINE")
        hdr.setObjectName("TLabel")
        hdr.setStyleSheet("font-size:10px; letter-spacing:1px;")
        self._feedback_layout.addWidget(hdr)

        grid = QGridLayout()
        grid.setSpacing(4)
        for idx, action in enumerate(result.actions):
            bar = SolverFrequencyBar(action.action, action.frequency, action.ev, action.sizing)
            grid.addWidget(bar, idx // 2, idx % 2)
        self._feedback_layout.addLayout(grid)

        conf = QLabel(f"Source: {result.source_confidence}")
        col = _AMBER if "Mock" in result.source_confidence else _GREEN
        conf.setStyleSheet(f"font-family:'JetBrains Mono',monospace; font-size:9px; color:{col};")
        self._feedback_layout.addWidget(conf)

    def _show_drill_feedback(self, hero_action_str: str) -> None:
        _clear(self._feedback_layout)
        drill = self._current_drill
        if drill is None:
            return

        result = compare_action(drill, hero_action_str)
        score = score_decision(result["ev_loss"], result["solver_frequency"])
        self.lib.record_score(drill["id"], score)
        self.state.record_decision(
            result["is_correct"], result["ev_loss"],
            f"{drill['id']} {hero_action_str}: -{result['ev_loss']:.2f}bb"
        )

        # Score chip
        col = _GREEN if result["is_correct"] else _RED
        verdict_lbl = QLabel(
            f"{'✓' if result['is_correct'] else '✗'}  {hero_action_str.upper()}"
        )
        verdict_lbl.setStyleSheet(
            f"font-family:'JetBrains Mono',monospace; font-size:13px; "
            f"font-weight:700; color:{col};"
        )
        self._feedback_layout.addWidget(verdict_lbl)

        detail = QLabel(
            f"Best: {result['best_action']}  |  EV loss: {result['ev_loss']:+.2f}bb\n"
            f"Score: {score}/100  ({skill_label(score)})"
        )
        detail.setObjectName("Muted")
        detail.setWordWrap(True)
        detail.setStyleSheet("font-size:10px;")
        self._feedback_layout.addWidget(detail)
        self._feedback_layout.addWidget(_sep())

        # Mini solver grid
        hdr = QLabel("SOLVER FREQUENCIES")
        hdr.setObjectName("TLabel")
        hdr.setStyleSheet("font-size:10px;")
        self._feedback_layout.addWidget(hdr)
        grid = QGridLayout()
        grid.setSpacing(4)
        for idx, action in enumerate(result["solver"]["actions"]):
            bar = SolverFrequencyBar(
                action["action"], action["frequency"],
                action["ev"], action.get("sizing", "")
            )
            grid.addWidget(bar, idx // 2, idx % 2)
        self._feedback_layout.addLayout(grid)

        # Update score bar
        self._score_total_lbl.setText(f"Last score: {score}/100  {skill_label(score)}")
        self.coach_message.emit(explain_spot(drill, hero_action_str))

    # ── Keyboard shortcuts ─────────────────────────────────────────────

    def _space_pressed(self) -> None:
        if hasattr(self, "_next_drill_btn") and self._next_drill_btn.isVisible():
            self._play_next()
        elif self._game and not self._game.is_waiting_for_hero:
            pass   # bots are running, let them finish

    def _key_action(self, key: str) -> None:
        if not self._game or not self._game.is_waiting_for_hero:
            return
        if key == "F" and self.fold_btn.isVisible():
            self.fold_btn.click()
        elif key == "C":
            if self.call_btn.isVisible():
                self.call_btn.click()
            elif self.check_btn.isVisible():
                self.check_btn.click()
        elif key == "R" and self.raise_btn.isVisible():
            self.raise_btn.click()
        elif key == "A" and self.allin_btn.isVisible():
            self.allin_btn.click()
